apiVersion: v1
kind: Secret
metadata:
  labels:
    app: "{{ template "influxdb.fullname" . }}"
    chart: "{{ template "influxdb.chart" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "influxdb.fullname" . }}-auth
data:
  INFLUXDB_USER: {{ .Values.elastisys_custom.influxdb_user | b64enc }}
  INFLUXDB_PWD: {{ .Values.elastisys_custom.influxdb_password | b64enc }}
